version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - run:
          name: Install NPM
          command: npm install

      - run:
        name: Test
        command: |
          npm run lint

      - run:
        name: Test
        command: |
          npm run test:cover


      - run:
        name: Test
        command: |
          npm run coveralls
